### ISSUE TITLE
Why the library doesn't load in a controller?

### ISSUE THREAD

**Issue by vicenrele** [biozshock/crontab#2]
Hello.
I've a problem with crontab library. If I try the library to loading and using it in principal controller, it works perfectly, but not if I try it in another controller which receives Ajax requests. Do you know why?

Edit: The problem is in the load of the library: `$this->load->library('crontab');` 
If the library is loaded (I try in contructor, in index() function or in another function) the Ajax requests don't be done

Thanks.

**Comment by biozshock** [comment]
does it show any errors?

**Comment by vicenrele** [comment]
I capture errors with log_message function and it doesn't show errors. Simply, the Ajax request ins't done. A message is shown by error function of Ajax called. A message set by me

**Comment by biozshock** [comment]
If there are no error in logs then error somewhere else, and definitely not in this library.
